language: python

python:
  - 3.5

cache: pip

install:
  - pip install -q -r requirements.txt
  - pip install -q flake8
  - pip install -q codecov

script:
  - flake8 .
  - bash run_tests.sh

after_success:
  - codecov

notifications:
  email: false

branches:
  only:
    - master
